config/routes.rb
Rails.application.routes.draw do
  devise_for :admin,skip: [:registrations, :passwords],  controllers: {
  sessions: "admin/sessions"
}


scope module: :public do
  root to:'homes#top'
  get "/homes" => "homes#top"
  get "/homes/about" => "homes#about"

  resources :items,         only:[:index, :show]

  resource :customers,     only:[:show, :update]
  get "/customers/edit1" => "customers#edit"
  get "/customers/confirm" => "customers#confirm"
  patch "/customers/withdrawal" => "customers#withdrawal"

  delete "/cart_items/destroy_all" => "cart_items#destroy_all"
  resources :cart_items,    only:[:index, :update, :destroy, :create]

  resources :orders,        only:[:new, :create, :index, :show] do
    collection do
  get "/confirm" => "orders#confirm"
  get "/conpletion" => "orders#conpletion"
end
end
  resources :addresses,     only:[:index, :edit, :create, :update, :destroy]
end


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

namespace :admin do
  get "/homes" => "homes#top"
  resources :items
  resources :genres,        only:[:index, :create, :edit, :update]
  resources :customers,     only:[:index, :show, :edit, :update]
  resources :orders,        only:[:show, :update]
  resources :order_details, only:[:update]
end


  #devise_for :admins
  #devise_for :customers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer


  def subtotal
    item.with_tax_price * self.amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :addresses
  has_many :orders
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

   def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
   end

   def  with_tax_price
    (price * 1.1).floor
   end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_details
    belongs_to :customer
    enum payment_method: {credit_card: 0, transfer: 1}
    enum status: {awaiting_payment: 0, payment_confirmation: 1, under_manifacture: 2, preparing_to_ship: 3, already_shipped: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: {not_available: 0, awaiting_production: 1, under_manifacture: 2, completed_production: 3}

   def subtotal
    price_including_tax * self.amount
   end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page])

  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:id, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

 def index
    @genres = Genre.all
    @genre = Genre.new
 end

 def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
 end

 def edit
    @genre = Genre.find(params[:id])
 end

 def update
   @genre = Genre.find(params[:id])
   @genre.update(genre_params)
   redirect_to admin_genres_path
 end

private

 def genre_params
  params.require(:genre).permit(:name)
 end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @orders = Order.page(params[:page]).per(10)
    @amount = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all

  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])

  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
     @item = Item.find(params[:id])
     @item.update(item_params)
     redirect_to admin_item_path(@item.id)
  end


  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @orders = Order.page(params[:page])
    @order = Order.find(params[:id])
    @order_details = @order.order_details

  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path(@order.id)
  end


private
  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :status, :created_at)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_homes_path
    else
        root_path
    end
 end

 def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
 end

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
 end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    
<h3>会員情報編集</h3>
</br>
 <%= form_with model: @customer, url: admin_customer_path do |f| %>

<p>
 <strong>会員ID</strong>
 <%= @customer.id %>
</p>

<p>
<div class="form-group">
   <label for="inputName">氏名</label></br>
   <%= f.text_field :last_name, autofocus: true, id:"inputName" %><%= f.text_field :first_name, autofocus: true, id:"inputName" %></br>
</div>
</p>

<p>
<div class="form-group">
   <label for="inputKanaName">フリガナ</label></br>
   <%= f.text_field :last_name_kana, autofocus: true, id:"inpuKanatName" %><%= f.text_field :first_name_kana, autofocus: true, id:"inputKanaName" %></br>
</div>
</p>

<p>
 <div class="form-group">
  <label for="inputPostalCode">郵便番号</label>
   <%= f.text_field :postal_code, autofocus: true, id:"inputPostalCode" %>
 </div>
</p>

<p>
  <div class="form-group">
    <label for="inputAddress">住所</label>
    <%= f.text_field :address, autofocus: true, id:"inputAddress" %>
  </div>

</p>

<p>
  <div class="form-group">
  <label for="inputTerephoneNumber">電話番号</label>
  <%= f.text_field :telephone_number, autofocus: true, id:"inputTelephoneNumber" %>
</p>

<p>
  <div class="form-group">
  <label for="inputEmail">メールアドレス</label>
  <%= f.email_field :email, autofocus: true, id:"inputEmail" %>
</p>

<p>
  <div class="form-group">
    <label for="inputIsDeleted">会員ステータス</label></br>
  <%= f.radio_button  :is_deleted, false %>有効 <%= f.radio_button :is_deleted, true %>退会
</p>

  <%= f.submit "変更を保存", class:"btn btn-secondary btn-sm" %>

 <% end %>
  </div>
 </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
 <div class="row">
  <div class="mx-auto col-12">
   <h3>会員一覧</h3>
   </br>

   <table class="table table-sm">
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>

    <tbody>
     <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td>
         <%= link_to admin_customer_path(customer.id) do %>
          <%= customer.last_name %><%= customer.first_name %>
         <% end %>
         </td>
        <td><%= customer.email %></td>
        <td>
         <% if customer.is_deleted == true %>退会
          <% else %>有効
         <% end %></td>
      </tr>
      <% end %>
      <%= paginate @customers %>
    </tbody>
   </table>
  </div>
 </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
 <div class="row">
  <div class="col-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

    <div class="card w-75">
      <div class="card-body">
        <h5 class="card-title">会員詳細</h5>
        <p class="card-text">会員ID：         <%= @customer.id %></p>
        <p class="card-text">氏名：           <%= @customer.last_name %> <%= @customer.first_name %></p>
        <p class="card-text">フリガナ：       <%= @customer.last_name_kana %> <%= @customer.first_name_kana %></p>
        <p class="card-text">郵便番号：       <%= @customer.postal_code %></p>
        <p class="card-text">住所：           <%= @customer.address %></p>
        <p class="card-text">電話番号：       <%= @customer.telephone_number %></p>
        <p class="card-text">メールアドレス： <%= @customer.email %></p>
        <p class="card-text">
          会員ステータス：
          <% if @customer.is_deleted == true %>退会
            <% else %>有効
          <% end %>
        </p>
        <p>
         <%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success btn-sm" %>

         <%= link_to "注文履歴一覧を見る", admin_homes_path, class:"btn btn-primary btn-sm" %>
        </p>
      </div>
    </div>
  </div>
 </div>
</div>