config/routes.rb
Rails.application.routes.draw do
  devise_for :admin,skip: [:registrations, :passwords],  controllers: {
  sessions: "admin/sessions"
}


scope module: :public do
  root to:'homes#top'
  get "/homes" => "homes#top"
  get "/homes/about" => "homes#about"

  resources :items,         only:[:index, :show]

  resource :customers,     only:[:show, :update]
  get "/customers/edit1" => "customers#edit"
  get "/customers/confirm" => "customers#confirm"
  patch "/customers/withdrawal" => "customers#withdrawal"

  delete "/cart_items/destroy_all" => "cart_items#destroy_all"
  resources :cart_items,    only:[:index, :update, :destroy, :create]

  resources :orders,        only:[:new, :create, :index, :show] do
    collection do
  get "/confirm" => "orders#confirm"
  get "/conpletion" => "orders#conpletion"
end
end
  resources :addresses,     only:[:index, :edit, :create, :update, :destroy]
end


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

namespace :admin do
  get "/homes" => "homes#top"
  resources :items
  resources :genres,        only:[:index, :create, :edit, :update]
  resources :customers,     only:[:index, :show, :edit, :update]
  resources :orders,        only:[:show, :update]
  resources :order_details, only:[:update]
end


  #devise_for :admins
  #devise_for :customers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer


  def subtotal
    item.with_tax_price * self.amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :addresses
  has_many :orders
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

   def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
   end

   def  with_tax_price
    (price * 1.1).floor
   end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_details
    belongs_to :customer
    enum payment_method: {credit_card: 0, transfer: 1}
    enum status: {awaiting_payment: 0, payment_confirmation: 1, under_manifacture: 2, preparing_to_ship: 3, already_shipped: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: {not_available: 0, awaiting_production: 1, under_manifacture: 2, completed_production: 3}

   def subtotal
    price_including_tax * self.amount
   end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

 def index
    @genres = Genre.all
    @genre = Genre.new
 end

 def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
 end

 def edit
    @genre = Genre.find(params[:id])
 end

 def update
   @genre = Genre.find(params[:id])
   @genre.update(genre_params)
   redirect_to admin_genres_path
 end

private

 def genre_params
  params.require(:genre).permit(:name)
 end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @orders = Order.page(params[:page]).per(10)
    @amount = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all

  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])

  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
     @item = Item.find(params[:id])
     @item.update(item_params)
     redirect_to admin_item_path(@item.id)
  end


  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @orders = Order.page(params[:page])
    @order = Order.find(params[:id])
    @order_details = @order.order_details

  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path(@order.id)
  end


private
  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :status, :created_at)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_homes_path
    else
        root_path
    end
 end

 def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
 end

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
 end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h3>ジャンル編集</h3>

    <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>

    <div class="form-group">
    <label for="InputName">ジャンル名</label>
    <%= f.text_field :name, autofocus: true, id:"InputName" %>
    </div>

    <%= f.submit "変更を保存" , class:"btn btn-success btn-sm" %>

    <% end %>
  </div>
 </div>
</div>

app/views/admin/genres/index.html.erb
<h2>ジャンル一覧、追加</h2>

<div class="container">
  <div class="row">
 <%= form_with model: @genre, url: admin_genres_path do |f| %>

  <label for="genre_name">ジャンル名</label></br>
  <%= f.text_field :name %>

  <%= f.submit '新規投稿', class:"btn btn-success btn-sm" %>

 <% end %>
<div class="col-md-8">
<table class="table table-sm">
  <thead>
   <tr>
    <th scope="col">ジャンル</th>
    <th colspan="3"></th>
   </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
    <tr>
      <td><%= genre.name %></td>
　　　<td><%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-success btn-sm" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h3>商品編集</h3></br>

   <table>
      <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>
     <tr>
      <th><label for="image">商品画像</label></th>
      <td><%= f.file_field :image, accept: "image/*" %></td>
     </tr>
   
     <tr>
      <th><label for="name">商品名</label></th>
       <td><%= f.text_field :name, placeholder:"商品名"%></td>
     </tr>
   
     <tr>
      <th><label for="introduction">商品説明</label></th>
       <td><%= f.text_area :introduction, placeholder:"ここに説明文を記述します" %></td>
     </tr>
   
     <tr>
       <th><label for="genre_id">ジャンル</label></th>
       <td><%= f.collection_select :genre_id, @genres, :id, :name %></td>
     </tr>
   
     <tr>
      <th><label for="proce">税抜価格</label></th>
       <td><%= f.text_field :price, placeholder:"1000" %></td>
     </tr>
   
     <tr>
      <th><label for="is_active">販売ステータス</label></th>
      <td>
       <%= f.radio_button :is_active, true %>
       <%= f.label :is_active, "販売中" %>
   
       <%= f.radio_button :is_active, false %>
       <%= f.label :is_active, "販売中止" %>
       </td>
     </tr>

     <p><%= f.submit '変更を保存', class:"btn btn-success btn-sm" %></p>
    <% end %>

   </table>
  </div>
 </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h3>商品一覧</h3>

   <%= link_to "商品新規登録", new_admin_item_path, class:"btn btn-secondary btn-sm" %>
   <table  class="table table-sm">
    <thead>
       <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th colspan="3"></th>
        <th>ステータス</th>
       </tr>
    </thead>

    <tbody>
     <% @items.each do |item| %>
       <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item.id) %></td>
        <td><%= item.price %></td>
        <td><%= item.genre.name %></td>
        <td colspan="3"></td>
        <td>
         <% if item.is_active == true %>販売中
          <% else %>販売中止
         <% end %>
        </td>
       </tr>
     <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
 <div class="row">
  <div class="col-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h3>商品新規登録</h3></br>

   <table>
       <%= form_with model: @item, url: admin_items_path do |f| %>
     <tr>
      <th><label for="image">商品画像</label></th>
      <td><%= f.file_field :image, accept: "image/*" %></td>
     </tr>

     <tr>
      <th><label for="name">商品名</label></th>
       <td><%= f.text_field :name, placeholder:"商品名"%></td>
     </tr>

     <tr>
      <th><label for="introduction">商品説明</label></th>
       <td><%= f.text_area :introduction, placeholder:"ここに説明文を記述します" %></td>
     </tr>

     <tr>
       <th><label for="genre_id">ジャンル</label></th>
       <td><%= f.collection_select :genre_id, @genres, :id, :name %></td>
     </tr>

     <tr>
      <th><label for="proce">税抜価格</label></th>
       <td><%= f.text_field :price, placeholder:"1000" %></td>
     </tr>

     <tr>
      <th><label for="is_active">販売ステータス</label></th>
      <td>
       <%= f.radio_button :is_active, true %>
       <%= f.label :is_active, "販売中" %>

       <%= f.radio_button :is_active, false %>
       <%= f.label :is_active, "販売中止" %>
       </td>
     </tr>

     <p><%= f.submit '新規登録', class:"btn btn-success btn-sm" %></p>
    <% end %>
   </table>
  </div>
 </div>
</div>

app/views/admin/items/show.html.erb
<h3>商品詳細</h3>
<div class="container">
 <div class="row">
   <div class="col-4 px-5 px-sm-0 mx-auto">

</br>
<%= image_tag @item.get_image(200, 200) %>
</div>
<div class="col-8 px-5 px-sm-0 mx-auto">
<table class="table">

     <tr>
      <th>商品名</th>
      <td><%= @item.name %></td>
     </tr>

     <tr>
      <th>商品説明</th>
      <td><%= @item.introduction %></td>
     </tr>

     <tr>
      <th>ジャンル</th>
      <td><%= @item.genre.name %></td>
     </tr>

     <tr>
      <th>税込価格（税抜価）</th>
      <td><%= @item.price %></td>
     </tr>

      <tr>
      <th>販売ステータス</th>
      <td>
      <% if @item.is_active == true %>販売中
       <% else %>販売中止
      <% end %>
      </td>
    </tr>
</table>
</div>
</div>

 <%= link_to "編集する", edit_admin_item_path, class:"btn btn-success btn-sm" %>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
   <div class="row">
    <div class="col-12 mx-auto">
    <h3>注文履歴詳細</h3>
    <table>
     <tr>
      <th>購入者</th>
      <td><%= @order.name %></td>
     </tr>

     <tr>
      <th>注文日</th>
      <td><%= @order.created_at.strftime('%Y/%m/%d %H:%M') %></td>
     </tr>

     <tr>
      <th>配送先</th>
      <td>
       <%= @order.postal_code %><%= @order.address %></br>
       <%= @order.name %>
      </td>
     </tr>

     <tr>
      <th>支払方法</th>
      <td><%= @order.payment_method_i18n %></td>
     </tr>

     <tr>
      <th>注文ステータス</th>
      <td>
        <%= @order.status_i18n %>
         <%= form_with model: @order,url: admin_order_path(@order.id) do |f| %>
         <%= f.select :status, Order.statuses_i18n.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
         <%= f.submit "変更", class:"btn btn-success btn-sm" %>
        <% end %>
      </td>
     </tr>
    </table>
    </div>
   </div>
   </br>

    <div class="row">
     <div class="col-8 mx-auto">
     <table class="table table-hover table-inverse">
       <thead>
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
          <th></th>
        </tr>
       </thead>
        <% @total = 0  %>
       <tbody>
        <% @order_details.each do |order_detail| %>
         <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= order_detail.price_including_tax %></td>
          <td><%= order_detail.amount %></td>
          <td><%= order_detail.subtotal.to_i %></td>
          <% @total += order_detail.subtotal.to_i %>
          <td>
           <%= order_detail.making_status_i18n %>
            <%= form_with model: order_detail,url: admin_order_detail_path(order_detail.id) do |f| %>
             <%= f.select :making_status, OrderDetail.making_statuses_i18n.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
             <%= f.submit "変更", class:"btn btn-success btn-sm" %>
            <% end %>
          </td>
          <td></td>
         </tr>
         <% end %>
       </tbody>
      </table>
     </div>


<div class="col-4 mx-auto">
<table class="table table-bordered">
    <tr>
      <th>商品合計</th>
      <td><%= @total.to_i %><%= "円" %></td>
    </tr>

    <tr>
      <th>配送料</th>
       <td><%= @order.shipping_cost %><%= "円" %></td>
    </tr>

    <tr>
      <th>請求金額合計</th>
      <td><%= @order.shipping_cost.to_i + @total.to_i %><%= "円" %></td>
    </tr>
   </table>
  </div>
 </div>
</div>