config/routes.rb
Rails.application.routes.draw do
  devise_for :admin,skip: [:registrations, :passwords],  controllers: {
  sessions: "admin/sessions"
}


scope module: :public do
  root to:'homes#top'
  get "/homes" => "homes#top"
  get "/homes/about" => "homes#about"

  resources :items,         only:[:index, :show]

  resource :customers,     only:[:show, :update]
  get "/customers/edit1" => "customers#edit"
  get "/customers/confirm" => "customers#confirm"
  patch "/customers/withdrawal" => "customers#withdrawal"

  delete "/cart_items/destroy_all" => "cart_items#destroy_all"
  resources :cart_items,    only:[:index, :update, :destroy, :create]

  resources :orders,        only:[:new, :create, :index, :show] do
    collection do
  get "/confirm" => "orders#confirm"
  get "/conpletion" => "orders#conpletion"
end
end
  resources :addresses,     only:[:index, :edit, :create, :update, :destroy]
end


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

namespace :admin do
  get "/homes" => "homes#top"
  resources :items
  resources :genres,        only:[:index, :create, :edit, :update]
  resources :customers,     only:[:index, :show, :edit, :update]
  resources :orders,        only:[:show, :update]
  resources :order_details, only:[:update]
end


  #devise_for :admins
  #devise_for :customers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer


  def subtotal
    item.with_tax_price * self.amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :addresses
  has_many :orders
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

   def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
   end

   def  with_tax_price
    (price * 1.1).floor
   end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_details
    belongs_to :customer
    enum payment_method: {credit_card: 0, transfer: 1}
    enum status: {awaiting_payment: 0, payment_confirmation: 1, under_manifacture: 2, preparing_to_ship: 3, already_shipped: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: {not_available: 0, awaiting_production: 1, under_manifacture: 2, completed_production: 3}

   def subtotal
    price_including_tax * self.amount
   end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

 def index
    @genres = Genre.all
    @genre = Genre.new
 end

 def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
 end

 def edit
    @genre = Genre.find(params[:id])
 end

 def update
   @genre = Genre.find(params[:id])
   @genre.update(genre_params)
   redirect_to admin_genres_path
 end

private

 def genre_params
  params.require(:genre).permit(:name)
 end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @orders = Order.page(params[:page]).per(10)
    @amount = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all

  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])

  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
     @item = Item.find(params[:id])
     @item.update(item_params)
     redirect_to admin_item_path(@item.id)
  end


  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_homes_path
    else
        root_path
    end
 end

 def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
 end

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
 end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container">
        <a class="navbar-brand" href="/"><span>ながのけーき</span></a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
         </button>

         <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="justify-content-end ml-auto">
      <% if customer_signed_in? %>

      <%= link_to "マイページ", customers_path, class: "nav-link active btn btn-outline-primary" %>

      <%= link_to "商品一覧", items_path, class: "nav-link active btn btn-outline-primary" %>

      <%= link_to "カート", cart_items_path, class: "nav-link active btn btn-outline-primary" %>

      <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link active btn btn-outline-primary" %>


      <% elsif admin_signed_in? %>

      <%= link_to "商品一覧", admin_items_path, class: "nav-link active btn btn-outline-primary" %>

      <%= link_to "会員一覧", admin_customers_path, class: "nav-link active btn btn-outline-primary" %>

      <%= link_to "注文履歴一覧", admin_homes_path, class: "nav-link active btn btn-outline-primary" %>

      <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link active btn btn-outline-primary" %>

      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link active btn btn-outline-primary" %>

      <% else %>

      <%= link_to "About",  homes_about_path, class: "nav-link active btn btn-outline-primary" %>

      <%= link_to "商品一覧", items_path, class: "nav-link active btn btn-outline-primary" %>

      <%= link_to "新規登録", new_customer_registration_path, class: "nav-link active btn btn-outline-primary" %>

      <%= link_to "ログイン", new_customer_session_path, class: "nav-link active btn btn-outline-primary" %>

      <% end %>
          </ul>
         </div>
       </div>
      </nav>

    </header>
    <%= yield %>
    <footer>
     <div class='container mt-5'>
  	  <div class='row'>
  	   <div class='mx-auto'>
    	  	<p></p>
       	</div>
      </div>
     </div>
    </footer>
  </body>
</html>